### ISSUE TITLE
Handle predicates that takes collections

### ISSUE THREAD

**Issue by gaqzi** [senseyeio/mbgo#14]
I am in the process of migrating from static stubs into using mbgo to dynamically create them, and I discovered while setting up our dynamic stubs that some of our hardcoded ones use the `or` and `and` predicates. When we create a new stub the response will fail because mbgo is failing to parse these predicates.

To unblock myself I have just duplicated my stubs so I don't need to use `or` and `and`, because they were simple ways of providing the same response for multiple cases. Which I'm now creating on the fly instead. :)

An example predicate we had in our codebase.
```json
{
  "predicates": [
    {
      "or": [
        { "equals": { "method": "POST", "path": "/api/v2/payments/TestErrorMapping_Intent_ID:confirm" } },
        { "equals": { "method": "POST", "path": "/api/v2/intent/PurchasePay_Error:confirm" } },
        {
          "and": [
            { "equals": { "method": "POST", "path": "/api/v2/payments" } },
            { "equals": { "body": { "walletId": "error-wallet-id" } } }
          ]
        }
      ]
    }
  ]
}
```

**Comment by smotes** [comment]
PR https://github.com/senseyeio/mbgo/pull/15 includes support for nested predicates.
